language: android
sudo: false
android:
    components:
        - tools
        - build-tools-26.0.0
        - platform-tools
    licenses:
        - 'android-sdk-license-.+'
        - '.+'
script:
    - echo y | android update sdk --no-ui --all --filter extra-android-m2repository | grep 'package installed'
    - echo y | android update sdk --no-ui --all --filter extra-google-m2repository | grep 'package installed'
    - ./gradlew build check
