language: android
sudo: false
android:
    components:
        - tools
        - build-tools-26.0.0
        - platform-tools
    licenses:
        - 'android-sdk-license-.+'
        - '.+'
script:
    - echo y | sdkmanager "extras;android;m2repository"
    - echo y | sdkmanager "extras;google;m2repository"
    - ./gradlew build check
